### PR TITLE
Convert project to a PCL (so it can be used in Xamarin forms, etc).

### PR DESCRIPTION
**Pull request by PureKrome**
Hey @gustavofrizzo 

Ok - here's a PR for you, buddy.

It's basically converting the project into a PCL project so we can use it in a Xamarin Forms application (along with the usual .NET console apps or web apps).

While I was at it, I also did a quick clean up of some coding standards code (mainly `String` (urgh) to `string` (yay! :tada: ).

Finally, I've also included a nuget nuspec in there AND a powershell script so you can _easily_ deploy the nuspec (as a nupkg) to NuGet.org.

How? 

GLAD YOU ASKED!
- run powershell (and yeah yeah .. u need to have the correct _rights_ to run scripts)
- `cd <the project root directory>/NuGet Specs/`
- `./NuGet Deployment.ps1 -nuget C;\temp\nuget.exe -version 1.3.0.0 -apiKey <your nuget.org api key, found in your user profile>

(note: -nuget == the path to a `nuget.exe`)

that `NuGet Deployment.ps1` has a few other options, like how to create the package locally (don't provide an `-apikey <somevalue>` command line arg, for example.

also, typing `NuGet Deployment.ps1` without any args will show u the list of things you can do.

So yeah - hope this PR works and you're kewl with it. If so, ping me in this thread when you've updated NuGet.org :)

now, here's a rare tripple hug...

feels

### CODE REVIEW

**Comment by gustavo-frizzo** [comment]
Hey @PureKrome, 

Thanks for the PR!

I've learnt some new things with it. :D

About using "String", it's just a bad habit that I have and I need to change. hahaha

I will update the package in the next few days and then I will let you know. 

Cheers!

**Comment by PureKrome** [comment]
NP at all :)

also, hold off on the PR for a bit. I noticed you had/have Issue #1 so I'll refactor the sln to have .net 3.5/.net 4/PCL.

**Comment by gustavo-frizzo** [comment]
Ok.

My idea was to create several projects using the same source code, and use conditional compilation symbols to manipulate the differences between the versions.

I saw this solution in this project:

https://github.com/JamesNK/Newtonsoft.Json 

What do you think?

**Comment by PureKrome** [comment]
I've basically done something similar as his :)

I have used LINKED files with multi projects. the only diff is that i've put everything into one sln. he has separate ones per .NET framework.

This is the current screenie...

image

I'm not commited / pushed because i'm converting to xUnit for the tests..

code compiles, btw.

**Comment by gustavo-frizzo** [comment]
Oh, nice... :D

I've seen this solution in other projects too. Looks very organized.

Thanks!

**Comment by PureKrome** [comment]
:eyes:  @gustavofrizzo 

PR updated.

**Comment by PureKrome** [comment]
Yo  - ping :)

**Comment by PureKrome** [comment]
Thanks! (don't forget to publish to NuGet - i've made a script for you, to do that easily.

check in the `\NuGet\` folder.. and run a command like this: `& '.\NuGet Package and Publish.ps1' -version 0.1-alpha -nuget c:\temp\nuget.exe -apiKey ABCD-EFG..."` (where the apikey is your nuget.org api key)

**Comment by gustavo-frizzo** [comment]
Thanks @PureKrome 

Sorry for the delay, I was very busy these weeks. =p
Yeah... I'm going to publish soon. (Probably today)

If you find something wrong (in the process, package or something else) please tell me. I am just learning. :)

Best regards,
Gustavo Frizzo.

**Comment by PureKrome** [comment]
Will do mate! keep up the good work :)

**Comment by PureKrome** [comment]
Oh - and post in here when a new version has gone up to nuget (so we can test, etc).

**Comment by gustavo-frizzo** [comment]
The new version is up!
For some reason the script is not working on my machine but I will research about this later.

**Pull request merged**
