### PR TITLE
.NET Core support & Travis-CI integration

### PR DESCRIPTION
**Pull request by semack**
- Added .NET Core project.
- Added Travis-CI integration scripts 
- Updated .nuspec file
- Fixed Unit tests on Travis-CI using NUnit
- Removed old PowerShell scripts
- Enabled automatically publishing to Nuget 
- Added Travis-CI status to Readme.Md

Do not forget to configure ENV variables in Repository Settings on Travis-CI
screen shot 2017-10-24 at 14 01 12

### CODE REVIEW

**Comment by gustavo-frizzo** [comment]
Hey @semack ,

Thanks for the PR!

I will update the package this weekend.

Best regards,
Gustavo Frizzo.

**Comment by semack** [comment]
Great, thank you. If you need my assistance with Travis, just let me know.

**Comment by gustavo-frizzo** [comment]
Cool. Travis is something new for me.
Sorry, I could not finish it this weekend. (Life is busy...)
I will let you know if I need help. 
Thanks!

**Comment by semack** [comment]
@gustavofrizzo, Could you please update nuget package?

**Comment by gustavo-frizzo** [comment]
@semack,
Done. It will appear in search results and will be available for install/restore after nuget indexing is complete.

**Comment by semack** [comment]
Ok. Thank you

--
Kind regards,
Andriy S'omak

**Pull request merged**
